name: Build, Test, and Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to PyPI'
        required: false
        type: boolean

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
    - name: Install dependencies
      run: |
        poetry install
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code with Flake8
      run: |
        flake8 .

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
    - name: Bump version and tag
      run: |
        poetry version patch
        git config --local user.email "action@github.com"
        git config --local read-only false
        git config --local user.name "GitHub Action"
        git commit -am "Bump version"
        git tag v$(poetry version -s)
        git push origin HEAD --tags
    - name: Build and publish to PyPI
      run: |
        poetry build
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
    - name: Clean up
      run: |
        rm -rf dist
