name: Build, Test, and Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}  # Important for pull requests, defaults to the branch or commit that triggered the workflow for pushes

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Analysing the code with Flake8
      run: |
        flake8 .

    - name: Bump version and tag
      run: |
        poetry version minor
        NEW_VERSION=$(poetry version --short)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml
        git commit -m "Bump version to $NEW_VERSION"
        git checkout -B "${{ github.ref_name }}"
        git pull --rebase origin "${{ github.ref_name }}"
        if [ $? -eq 0 ]; then
          git push origin "${{ github.ref_name }}"
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"
        else
          echo "Failed to rebase, please check for conflicts or remote changes."
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish to PyPI
      run: |
        poetry build
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

    - name: Clean up
      if: always()
      run: |
        rm -rf dist
